name: Build FMSWRT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: awalsh128/cache-apt-pkgs-action@latest
        name: Install Dependencies
        with:
          packages: build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
          version: 1.4.3
          execute_install_scripts: true


      # Copies the configuration needed.
      - name: Copy config and feeds
        run: |
          cp fmswrt-config openwrt/.config
          cp feeds.conf openwrt/feeds.conf

      # Install the feeds
      - name: Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # Install the feeds
      - name: Build
        working-directory: ./openwrt
        run: |
          make -j$(nproc) V=s

      # Upload Result
      - uses: actions/upload-artifact@v4
        with:
          name: built
          path: openwrt/bin/targets/bcm27xx/bcm2711
            
